#!/usr/bin/env node
/**
 * scripts/setup-local.js
 *
 * Run automatically via `npm run dev:local` (through the predev:local hook)
 * or manually via `npm run setup:local`.
 *
 * What it does:
 *  1. Detects the machine's LAN IP using os.networkInterfaces()
 *     (skips loopback and virtual Docker/VM adapters).
 *  2. Writes (or overwrites) mobile/.env with EXPO_PUBLIC_API_URL
 *     so the Expo Go app on a phone can reach the backend over the LAN.
 *  3. Patches backend/.env to add the LAN IP to ALLOWED_ORIGINS so the
 *     Expo web client and Metro bundler can make CORS-safe requests.
 *
 * This script requires only Node.js built-ins (os, fs, path) — no install needed.
 */

'use strict';

const os   = require('os');
const fs   = require('fs');
const path = require('path');

// ── Root paths ───────────────────────────────────────────────────────────────
const ROOT            = path.join(__dirname, '..');
const MOBILE_ENV      = path.join(ROOT, 'mobile', '.env');
const BACKEND_ENV     = path.join(ROOT, 'backend', '.env');
const BACKEND_EXAMPLE = path.join(ROOT, 'backend', '.env.example');

// ── 1. Detect LAN IP ─────────────────────────────────────────────────────────
function getLanIp() {
  const nets = os.networkInterfaces();
  for (const name of Object.keys(nets)) {
    // Skip loopback and well-known virtual adapter name prefixes
    if (/^(lo|docker|vmnet|vEthernet|virbr|tun|tap|utun)/i.test(name)) continue;
    for (const iface of nets[name] ?? []) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  // Fallback: localhost (still useful for simulator-only testing)
  console.warn('⚠   Could not detect a LAN IP — falling back to 127.0.0.1.');
  console.warn('    Physical Expo Go devices will not be able to reach the backend.');
  console.warn('    Connect to a Wi-Fi network and re-run `npm run setup:local`.');
  return '127.0.0.1';
}

const ip     = getLanIp();
const apiUrl = `http://${ip}:3001`;

// ── 2. Write mobile/.env ─────────────────────────────────────────────────────
const mobileEnvContent = [
  '# Auto-generated by scripts/setup-local.js',
  '# Re-run "npm run setup:local" whenever your IP address changes.',
  '',
  `EXPO_PUBLIC_API_URL=${apiUrl}`,
  '',
].join('\n');

fs.writeFileSync(MOBILE_ENV, mobileEnvContent, 'utf8');
console.log(`✅  mobile/.env        → EXPO_PUBLIC_API_URL=${apiUrl}`);

// ── 3. Patch backend/.env ALLOWED_ORIGINS ────────────────────────────────────
//
// Adds the LAN IP origins to ALLOWED_ORIGINS so the backend does not reject
// CORS pre-flight requests from the Expo web client or Metro bundler.
// (Native Expo Go on a device does not trigger CORS, but this is future-proof.)
//
// The patch is idempotent — running setup twice won't duplicate entries.
//
if (fs.existsSync(BACKEND_ENV)) {
  let envText = fs.readFileSync(BACKEND_ENV, 'utf8');

  const expoLanOrigin  = `http://${ip}:8081`;
  const expoExpOrigin  = `exp://${ip}:8081`;
  const originLine     = envText.match(/^ALLOWED_ORIGINS=(.*)$/m);

  if (originLine) {
    const existing = originLine[1];
    const parts    = existing.split(',').map(s => s.trim()).filter(Boolean);

    let changed = false;
    for (const origin of [expoLanOrigin, expoExpOrigin]) {
      if (!parts.includes(origin)) {
        parts.push(origin);
        changed = true;
      }
    }

    if (changed) {
      envText = envText.replace(
        /^ALLOWED_ORIGINS=.*$/m,
        `ALLOWED_ORIGINS=${parts.join(',')}`
      );
      fs.writeFileSync(BACKEND_ENV, envText, 'utf8');
      console.log(`✅  backend/.env       → ALLOWED_ORIGINS patched with LAN origins`);
    } else {
      console.log(`✅  backend/.env       → ALLOWED_ORIGINS already up-to-date`);
    }
  } else {
    // ALLOWED_ORIGINS line doesn't exist yet — seed from .env.example, then add LAN origins.
    // This keeps the default origins in a single source of truth (.env.example).
    let baseOrigins = 'http://localhost:5173,http://localhost:4173,http://localhost:8081';
    if (fs.existsSync(BACKEND_EXAMPLE)) {
      const exampleLine = fs.readFileSync(BACKEND_EXAMPLE, 'utf8').match(/^ALLOWED_ORIGINS=(.*)$/m);
      if (exampleLine) baseOrigins = exampleLine[1].trim();
    }
    const appended = `\n# Added by setup-local.js\nALLOWED_ORIGINS=${baseOrigins},${expoLanOrigin},${expoExpOrigin}\n`;
    fs.appendFileSync(BACKEND_ENV, appended, 'utf8');
    console.log(`✅  backend/.env       → ALLOWED_ORIGINS added`);
  }
} else {
  console.warn('⚠   backend/.env not found — skipping ALLOWED_ORIGINS patch.');
  console.warn('    Copy backend/.env.example to backend/.env and re-run this script.');
}

// ── Summary ──────────────────────────────────────────────────────────────────
console.log('');
console.log('📱  Scan the Expo QR code with Expo Go on a device connected to the same Wi-Fi.');
console.log(`🔗  Backend URL: ${apiUrl}`);
console.log('');
